name: ms2-mu
channels:
  - defaults
dependencies:
  - pytorch==1.12.1
  - defaults/linux-64::numpy==1.20.3
  - defaults/linux-64::matplotlib==3.4.2
  - defaults/noarch::seaborn==0.11.2
  - defaults/linux-64::pandas==1.3.2
  - bioconda::blast
  - defaults/linux-64::jupyter==1.0.0
  - defaults/linux-64::python==3.9.5
  - pip
  - dill
  - biopython
  - arviz

