name: ms2-mu
channels:
  - defaults
  - pytorch
  - bioconda
dependencies:
  - pytorch==1.9.1
  - numpy==1.20.3
  - matplotlib==3.4.2
  - scipy==1.7.1
  - seaborn==0.11.2
  - pandas==1.3.2
  - bioconda::blast
  - jupyter==1.0.0
  - python==3.9.5
  - pip
  - dill
  - biopython
  - arviz
